// <auto-generated />
using System;
using ILikeTram.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ILikeTram.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ILikeTram.Model.Route", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TramRoutes");
                });

            modelBuilder.Entity("ILikeTram.Model.Tram", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Trams");
                });

            modelBuilder.Entity("ILikeTram.Model.TramStop", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RouteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RouteId");

                    b.ToTable("TramStops");
                });

            modelBuilder.Entity("ILikeTram.Model.TramStop", b =>
                {
                    b.HasOne("ILikeTram.Model.Route", null)
                        .WithMany("StopsList")
                        .HasForeignKey("RouteId");
                });

            modelBuilder.Entity("ILikeTram.Model.Route", b =>
                {
                    b.Navigation("StopsList");
                });
#pragma warning restore 612, 618
        }
    }
}
